### ISSUE TITLE
Tracking issue: Version 0.1

### ISSUE THREAD

**Issue by druskus20** [druskus20/templar#1]
# Objectives
- [ ] Basic configuration through Lua
  - [x] Convert back and forward between Lua and Rust types
  - [x] Expose Rust functions to Lua ergonomically (done through `lua-export`)
  - [x] Generate a Lua module to hide undefined function warnings (done through `lua-export`)
  - [ ] **WIP** Config should be based on a nested set of rules. Handle specificity and calculate the target files for each rule
  - [ ] Allow specifying priorities for templating rules (before / after)
  - [ ] Define and implement a config API 
- [ ] Basic parsing of templates 
  - [x] Parse templates with tokens defined at runtime 
  - [x] Generate text from templating directives
  - [ ] Define and implement a set of templating directives
      - [ ] **WIP** Basic operations such as `If`, `IfElse`, `For`
      - [ ] **WIP** A flexible `Transform` directive that runs lua over a fragment of a template
      - [ ] Definition of variables at different scopes (template-level, global, local...)
- [ ] Template processing
  - [ ] **WIP**: Generate text from template directives
  - [ ] Handle variable contexts properly (there might be problems when running templates in parallel)
  - [ ] Build a dependency graph to apply rules in parallel
- [ ] Commands
  - [x] Use StructOpt to document cli options
  - [ ] A command to prepare templar (among others, generate the Lua config module)
  - [ ] A command to run Templar with a given config
  - [ ] A command to scan existing configs for things to template (for example, hex color codes)
  - [ ] A command to detect conflicts between a parser config and a given file?
- [ ] Documentation and testing
  - [ ] Document the Lua config library
  - [ ] Document the templating syntax
  - [ ] **WIP** A reasonable amount of tests, before release, the template parser and config API should be well tested
  - [ ] Docs should be autogenerated from comments
- [ ] Website
  - [ ] Create a simple static site for presentation and docs
